---
# tasks file for k8s
# - { include: update-bin.yml, tags: ['update'] }
# - { include: configure.yml, tags: ['configure']}
- name: get service
  shell: ls -l /usr/lib/systemd/system/
  register: result

- { include: set-service.yml, tags: ['configure']}
- { include: update-api-server-service.yml, tags: ['configure']}