---
- name: Give insecure permissions to an existing file
  file:
    path: "{{ bin_path_to }}"
    owner: root
    group: root
    state: directory

- name:
  copy:
    src: "{{ bin_path_from }}/"
    dest: "/home/go/bin/"
    owner: root
    group: root
    mode: '0655'
