---
- name: copy service to /usr/lib/systemd/system/
  copy:
    src: "service-tmp/{{ item }}"
    dest: "/usr/lib/systemd/system/"
    owner: root
    group: root
    mode: '0755'
  loop:
    - etcd.service
    - kube-apiserver.service
    - kube-controller-manager.service
    - kube-scheduler.service