---
# tasks file for kubadm-management
- name: debug info
  debug: msg="image_repository={{image_repository}} service_subnet={{service_subnet}} advertise_address={{advertise_address}}"
- block:
  - name: create default init config
    template: src=kubeadm.conf.j2 dest=kubeadm.conf

  - name: swapoff -a
    shell: swapoff -a && kubeadm reset --force

  - name: start master
    shell: kubeadm init --config=kubeadm.conf
    register: start_info

  - name: debug
    shell: echo "{{ start_info.stdout|regex_search('kubeadm join \\d+.\\d+.\\d+.\\d+:\\d+')}} {{start_info.stdout|regex_search('--token .+')}} {{start_info.stdout|regex_search('--discovery-token-ca-cert-hash sha256:.+')}}" > join.conf

  delegate_to: api_server
  become: yes
