---

- name: docker info
  shell: docker version
  become: yes
  register: docker_version
  ignore_errors: true

- name: apt update
  set_fact:
    docker_version_info: "{{ docker_version.stdout|regex_search('Version:\\s+(\\d+.\\d+.\\d+)')|regex_replace('Version:\\s+', '')}}"
  when: docker_version.stdout != ""

- name: install
  block:
  
    - name: plder version, remove!!!
      apt:
        name:
          - docker
          - docker-engine
          - docker.io
          - containerd runc
        purge: true
        state: absent
      become: yes
 
    - debug: msg="docker is not installed, try to install it."

    - name: apt update
      apt:
        update_cache: true
      become: yes

    - name: install docker depend
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl 
          - software-properties-common
      become: yes

    - name: add gpg
      shell: curl -fsSL https://mirrors.aliyun.com/docker-ce/linux/ubuntu/gpg | sudo apt-key add -
      become: yes

    - name: apt update
      apt:
        update_cache: true
      become: yes

    - name: install docker
      apt:
        name: docker.io
      become: yes
  when: "docker_version_info is undefined or docker_version_info is version('19.03.6', operator='lt')"